### ISSUE TITLE
should is "shifted" in hermes.cxx line 782 "shiftedmetric" ?

### ISSUE THREAD

**Issue by wphu** [bendudson/hermes-2#12]
In the hypnotoad code, parallel_transform = "shiftedmetric". 
should is "shifted" in hermes.cxx line 782 "shiftedmetric" ? otherwise, hermes-2 can not run with the hypnotoad generated grid.

**Comment by bendudson** [comment]
Thanks! I think this name was changed quite recently, so yes it should be updated in the input file.

**Comment by bendudson** [comment]
Fixed by cf72d57
